### ISSUE TITLE
Blockly data blocks not accessible

### ISSUE THREAD

**Issue by Mirodin** [javalikescript/lha#1]
First of I want to thank you for this awesome tool. Love to see a Lua driven home automation platform and will definitely evaluate to jump ship :)

However I could not test the blockly part because the data access block (I guess that is what it is) is broken in that it can not be dragged onto the working area (see below).

Reproducible on Void Linux with FF 109.0.1 and Chromium 111.0.5563.64.

![Screenshot 2023-04-01 at 06-48-32 Home](https://user-images.githubusercontent.com/2410346/229270575-de33a709-855c-4a9f-82e7-a64a79f86835.png)

**Comment by javalikescript** [comment]
Hello,

Thank you for reporting this issue and sorry for the late reply !

There is a bug in the blockly scripts when there is no writable things. You could workaround the issue by creating a generic basic thing.

I keep the issue open waiting for a fix. Feel free to open issue for bugs or missing features.

Have a good day,
Samuel
